name: "to_do_list"
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.19.2"
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  sqflite:
    version: ">=2.3.0"
  intl:
    version: ">=0.19.0"
  shared_preferences: ^2.2.2
